name: Build webpack project and deploy on gh-pages

on:
  push:
    branches: ["publish"]
  pull_request:
    branches: ["publish"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          git config --global user.name "gh-pages"
          npm install
          npm run deploy
